### PR TITLE
Fix muni contacts

### PR DESCRIPTION
**Pull request by jbothma**
to deploy new urls:
- load new muni data with sql/table_and_data_scorecard_geography.sql

to deploy staff contacts table name change:
- rename table municipality_contacts to municipality_staff_contacts
- merge and push to dokku

### CODE REVIEW

**Comment by jbothma** [comment]
my psql is giving a syntax error at the data copy stage with both the old and the new scorecard_geography script :/ I'm now on 9.5 - probably a version issue

**Comment by longhotsummer** [comment]
What's the error?

**Comment by jbothma** [comment]
Syntax error at 62 or whatever the first row of stdin is to the \copy
statement

**Comment by longhotsummer** [comment]
I piped through sql/table_and_data_geography.sql without hassle. The municipality_staff_contacts table already exists on the server, I'm going to assume it has the correct data.

I've merged this to master and am pushing now.

**Pull request merged**
